#This yaml replaces application.properties (analog)
spring:
    profiles:
        active:
          - dog
          - EN
          - prod #- dev
guru:
    username: YmlUserName
    password: YmlPassword
    jdbcurl: YmlUrl

#"SfgConfiguration" and "SfgConstructorConfig" classes contain @ConfigurationProperties("guru") annotation, which specifies
# properties of "guru" namespace from configuration file(s) [.properties or .yml], which will be injected into these classes by Spring

---
# ---   above means "new profile" for spring profile configuration in YAML format
spring:
    config:
        activate:
            on-profile: prod
guru:
    username: YmlProdDBUser
    password: YmlProdPassword
    jdbcurl: YmlURLforProdDB