#This yaml replaces application.properties (analog)
spring:
    profiles:
        active:
          - dog
          - EN
          - prod
guru:
    username: YmlUserName
    password: YmlPassword
    jdbcurl: YmlUrl

---
# --- above means "new profile" for spring profile configuration in YAML format
spring:
    config:
        activate:
            on-profile: prod
guru:
    username: YmlProdDBUser
    password: YmlProdPassword
    jdbcurl: YmlURLforProdDB